### ISSUE TITLE
Always super() constructor passing props as parameter.

### ISSUE THREAD

**Issue by raghuprathap** [shivamadurai/jsx-movie-cruiser#2]
Class component should always call base constructor with props.
![image](https://user-images.githubusercontent.com/3498847/43458682-c117146a-94e8-11e8-8ab6-625105f6172c.png)

**Comment by shivamadurai** [comment]
Done

**Comment by raghuprathap** [comment]
Please close the issue as well when we are done. I am closing it for now.
